version: '3'
networks:
  db:
  web:
services:
  db:
    image: mongo:3.4.10
    volumes:
      - ./data:/data/db
    networks:
      - db
  frontend:
    image: nginx:1.13
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - services
      - app
  services:
    image: node:9.2.0
    volumes:
      # Aplicação
      - ./wolke-services:/app
    working_dir: /app
    command: bash ./start.sh
    networks:
      - db
      - web
    depends_on:
      - db
    environment:
      - DB_NAME=wolke
      - DB_SERVER=db
  app:
    image: node:9.2.0
    volumes:
      # Aplicação
      - ./wolke-app:/app
    working_dir: /app
    command: bash ./start.sh
    networks:
      - web
    depends_on:
      - services
    environment:
      - DB_NAME=wolke
      - DB_SERVER=db
